name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
            deno-version: v1.x
      - name: Install dependencies
        run: |
          npm ci
          npm run build --if-present
      - name: Run tests
        run: |
          npm run test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
